### ISSUE TITLE
Create 3.1.1 release request

### ISSUE THREAD

**Issue by pongee** [Codeception/module-db#61]
hi

Could you please create the tag for 3.1.1 from master? 
Looks like the tag is missing, I assume it is a core problem for many users, since we use just tagged package (enterprise policy, I think it's not unique.)
For example it is missing from 3.1.0 tag but in master branch:
https://github.com/Codeception/module-db/pull/48

thank you.

best regards,
selyem

**Comment by Naktibalda** [comment]
https://github.com/Codeception/module-db/releases/tag/3.1.1
