### ISSUE TITLE
Issue having null values in database because of string type

### ISSUE THREAD

**Issue by guraurobi** [Codeception/module-db#65]
https://github.com/Codeception/module-db/blob/185889230bccfc65d2c03624879ade5357ec43f9/src/Codeception/Lib/Driver/Db.php#L348

This new addition broke all usages of haveInDatabase of null data for a certain column.

Example of fail:
`$I->haveInDatabase('table_name', ['column_name' => null]);`

Results in:

> [TypeError] Codeception\Lib\Driver\Db::isBinary(): Argument #1 ($string) must be of type string, null given, called in /app/vendor/codeception/module-db/src/Codeception/Lib/Driver/Db.php on line 297

**Comment by troy-rudolph** [comment]
Please merge https://github.com/Codeception/module-db/pull/63.  The fix is there.

**Comment by guraurobi** [comment]
Hey @troy-rudolph! Thanks so much for this fast fix, but please check my comments, might be useful!
