### ISSUE TITLE
[RFC] grabEntryFromDatabase

### ISSUE THREAD

**Issue by igorsantos07** [Codeception/module-db#9]
While testing a REST API I found myself needing an entire entry from the database to make sure my `GET /table/«id»` was implemented correctly.
However, I just found a method to retrieve a field from the database, not an entire entry.

As I'm not experienced with testing yet I would like to know some opinions about implementing a `grabEntryFromDatabase` method in the Db module, so we can use it to get pure information from the db and then use that to test what the system is doing.

Currently I'm using my own models to get the needed information, but this is the same the API is doing and the test is almost redundant...

Also, if there's any better practice on this, please let me know (:

**Comment by JesusTheHun** [comment]
9 years later, this basic functionality is still not implemented...
@eXorus would you at least accept a PR implementing this feature ?

**Comment by Naktibalda** [comment]
You are welcome to raise pull request.

Doctrine2 module got a similar feature in 2017: https://github.com/Codeception/Codeception/pull/4030

**Comment by eXorus** [comment]
Agree, you can do the PR, it's a feature I gonna use.

For now I'm using `executeInDatabase` to get multiples columns.

So we will have 
```php
$I->grabFromDatabase('users', 'email', ['id' => 123]);
// to get the email from the users table

$I->grabFromDatabase('users', ['email', 'name'], ['id' => 123]);
// to get the email and name from the users table
```

or with another method.

**Comment by JesusTheHun** [comment]
@eXorus as you can see in #43 , the API is : 

```php
$I->grabEntryFromDatabase('users', ['id' => 123])
```

I was hesitant to add a set of columns as parameter and I decided to go for brevity because it's a test so the bandwidth and the broad performance isn't relevant.

**Comment by Naktibalda** [comment]
Implemented by https://github.com/Codeception/module-db/pull/43
